# Generated by Django 4.0.6 on 2022-10-21 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainergy_dashboard.address'),
        ),
        migrations.CreateModel(
            name='BuildingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainergy_dashboard.address')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainergy_dashboard.building')),
            ],
            options={
                'verbose_name_plural': 'Building Addresses',
                'db_table': 'building_addresses',
            },
        ),
    ]
