# Generated by Django 4.0.6 on 2022-10-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0002_alter_building_address_buildingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingaddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='buildingaddress',
            name='building',
        ),
        migrations.RemoveField(
            model_name='building',
            name='address',
        ),
        migrations.AddField(
            model_name='building',
            name='address_line_1',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='city',
            field=models.CharField(default='', max_length=28),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='postal_code',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='province',
            field=models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut'), ('YT', 'Yukon')], default='AB', max_length=2),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='BuildingAddress',
        ),
    ]
