# Generated by Django 4.0.6 on 2022-10-28 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0003_remove_buildingaddress_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydata',
            name='building',
            field=models.ForeignKey(default='EjDwmtqy', on_delete=django.db.models.deletion.CASCADE, to='sustainergy_dashboard.building'),
            preserve_default=False,
        ),
    ]
