# Generated by Django 4.0.6 on 2022-11-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0004_dailydata_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='provider',
            field=models.CharField(choices=[('None', 'None'), ('Eyedro', 'Eyedro'), ('Opti-Mized', 'Opti-Mized')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='panel',
            name='serial',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
