# Generated by Django 4.0.6 on 2022-11-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0005_panel_provider_panel_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='timezone',
            field=models.CharField(choices=[('St. Johns', 'America/St_Johns'), ('Halifax', 'America/Halifax'), ('Glace Bay', 'Americca/Glace_Bay'), ('Moncton', 'America/Moncton'), ('Goose Bay', 'America/Goose_Bay'), ('Blanc Sablon', 'America/Blanc-Sablon'), ('Toronto', 'America/Toronto'), ('Nipigon', 'America/Nipigon'), ('Thunder Bay', 'America/Thunder_Bay'), ('Iqaluit', 'America/Iqaluit'), ('Pangnirtung', 'America/Pangnirtung'), ('Atikokan', 'America/Atikokan'), ('Winnipeg', 'America/Winnipeg'), ('Rainy Riger', 'America/Rainy_River'), ('Resolute', 'America/Resolute'), ('Rankin Inlet', 'America/Rankin_Inlet'), ('Regina', 'America/Regina'), ('Swift Current', 'America/Swift_Current'), ('Edmonton', 'America/Edmonton'), ('Cambridge Bay', 'America/Cambridge_Bay'), ('Yellowknife', 'America/Yellowknife'), ('Inuvik', 'America/Inuvik'), ('Creston', 'America/Creston'), ('Dawson Creek', 'America/Dawson_Creek'), ('Fort Nelson', 'America/Fort_Nelson'), ('Whitehorse', 'America/Whitehorse'), ('Dawson', 'America/Dawson'), ('Vancouver', 'America/Vancouver')], default='Edmonton', max_length=30),
        ),
    ]
