# Generated by Django 4.0.6 on 2022-11-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0005_panel_provider_panel_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='row_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
