# Generated by Django 4.0.6 on 2022-11-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0006_building_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='timezone',
            field=models.CharField(choices=[('America/St_Johns', 'St. Johns'), ('America/Halifax', 'Halifax'), ('Americca/Glace_Bay', 'Glace Bay'), ('America/Moncton', 'Moncton'), ('America/Goose_Bay', 'Goose Bay'), ('America/Blanc-Sablon', 'Blanc Sablon'), ('America/Toronto', 'Toronto'), ('America/Nipigon', 'Nipigon'), ('America/Thunder_Bay', 'Thunder Bay'), ('America/Iqaluit', 'Iqaluit'), ('America/Pangnirtung', 'Pangnirtung'), ('America/Atikokan', 'Atikokan'), ('America/Winnipeg', 'Winnipeg'), ('America/Rainy_River', 'Rainy Riger'), ('America/Resolute', 'Resolute'), ('America/Rankin_Inlet', 'Rankin Inlet'), ('America/Regina', 'Regina'), ('America/Swift_Current', 'Swift Current'), ('America/Edmonton', 'Edmonton'), ('America/Cambridge_Bay', 'Cambridge Bay'), ('America/Yellowknife', 'Yellowknife'), ('America/Inuvik', 'Inuvik'), ('America/Creston', 'Creston'), ('America/Dawson_Creek', 'Dawson Creek'), ('America/Fort_Nelson', 'Fort Nelson'), ('America/Whitehorse', 'Whitehorse'), ('America/Dawson', 'Dawson'), ('America/Vancouver', 'Vancouver'), ('Edmonton', 'America/Edmonton')], default='Edmonton', max_length=30),
        ),
    ]
