# Generated by Django 4.0.6 on 2022-11-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0006_circuit_row_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='circuit_amps',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='circuit_name',
            field=models.CharField(max_length=60),
        ),
    ]
