# Generated by Django 4.0.6 on 2022-11-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0007_alter_circuit_circuit_amps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='circuit_name',
            field=models.CharField(max_length=256),
        ),
    ]
