# Generated by Django 4.0.6 on 2022-11-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0008_alter_building_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyedroPanel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sustainergy_dashboard.panel',),
        ),
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='companies'),
        ),
    ]
