# Generated by Django 4.0.6 on 2022-11-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0008_alter_circuit_circuit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='panel_name',
            field=models.CharField(max_length=256),
        ),
    ]
