# Generated by Django 4.0.6 on 2022-11-22 00:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0009_eyedropanel_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='colour',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=[('#3649a8', 'Dark Blue'), ('#ee8f37', 'Orange'), ('#DB4B46', 'Red'), ('#3bcdee', 'Sky Blue'), ('#777777', 'Grey'), ('#994f9b', 'Purple'), ('#ffadc9', 'Light Pink'), ('#000000', 'Black'), ('#F7CA50', 'Yellow'), ('#98C355', 'Green'), ('#911120', 'Brown'), ('#C5BFE6', 'Light Purple'), ('#006ba9', 'Dark Sky'), ('#4DAAE8', 'Blue'), ('#FFFFE0', 'Light Yellow')]),
        ),
    ]
