# Generated by Django 4.0.6 on 2022-11-25 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0007_alter_circuit_circuit_amps_and_more'),
        ('sustainergy_dashboard', '0011_alter_panel_colour'),
    ]

    operations = [
    ]
