# Generated by Django 4.0.6 on 2022-11-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0009_alter_panel_panel_name'),
        ('sustainergy_dashboard', '0012_merge_20221124_2113'),
    ]

    operations = [
    ]
