# Generated by Django 4.0.6 on 2022-12-07 13:17

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0013_merge_20221129_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuitcategory',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
