# Generated by Django 4.0.6 on 2022-12-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0014_alter_circuitcategory_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STANDARD_USER', 'Standard User'), ('INSTALLER_USER', 'Installer User')], default='STANDARD_USER', max_length=20),
        ),
    ]
