# Generated by Django 4.0.6 on 2022-12-19 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0016_remove_circuitcategory_color_circuitcategory_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('meter_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField()),
                ('price_per_unit', models.DecimalField(decimal_places=3, max_digits=20)),
                ('usage', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('total_commodity', models.DecimalField(decimal_places=3, max_digits=20)),
                ('distribution', models.DecimalField(decimal_places=3, max_digits=20)),
                ('carbon_levy', models.DecimalField(decimal_places=3, default=0.0, max_digits=20)),
                ('gst', models.DecimalField(decimal_places=3, max_digits=20)),
                ('total_bill', models.DecimalField(decimal_places=3, max_digits=20)),
                ('statement_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=20)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainergy_dashboard.meter')),
            ],
        ),
        migrations.AddField(
            model_name='meter',
            name='meter_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainergy_dashboard.utility'),
        ),
    ]
