# Generated by Django 4.0.6 on 2022-12-19 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0017_meter_utility_utilitybill_meter_meter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainergy_dashboard.building'),
            preserve_default=False,
        ),
    ]
