# Generated by Django 4.0.6 on 2022-12-20 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0019_utilityprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='utility_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainergy_dashboard.utilityprovider'),
        ),
    ]
