# Generated by Django 4.0.6 on 2022-12-21 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0020_meter_account_number_meter_utility_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitybill',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sustainergy_dashboard.building'),
        ),
    ]
