# Generated by Django 4.0.6 on 2022-12-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0021_utilitybill_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilitybill',
            name='total_bill',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='total_commodity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='usage',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20),
            preserve_default=False,
        ),
    ]
