# Generated by Django 4.0.6 on 2022-12-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0022_alter_utilitybill_total_bill_n_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilitybill',
            name='billing_month',
        ),
    ]
