# Generated by Django 4.0.6 on 2023-01-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0023_remove_utilitybill_billing_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityBills',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Utility Bills',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sustainergy_dashboard.building',),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='carbon_levy',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='distribution',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='gst',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='usage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
