# Generated by Django 4.0.6 on 2023-01-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0025_panelmeter_newmeter_panelmeterchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelmeter',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
