# Generated by Django 4.0.6 on 2023-01-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0026_alter_panelmeter_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meter',
            options={'verbose_name_plural': 'Utility Meters'},
        ),
        migrations.RemoveField(
            model_name='panelmeterchannel',
            name='panel_meter',
        ),
        migrations.DeleteModel(
            name='PanelMeter',
        ),
    ]
