# Generated by Django 4.0.6 on 2023-01-25 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0027_alter_meter_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('panel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sustainergy_dashboard.panel')),
            ],
        ),
        migrations.AddField(
            model_name='panelmeterchannel',
            name='panel_meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainergy_dashboard.panelmeter'),
            preserve_default=False,
        ),
    ]
