# Generated by Django 4.0.6 on 2023-01-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0028_panelmeter_panelmeterchannel_panel_meter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panelmeterchannel',
            old_name='circuit_number',
            new_name='circuit_id',
        ),
    ]
