# Generated by Django 4.0.6 on 2023-01-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0029_rename_circuit_number_panelmeterchannel_circuit_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circuit',
            old_name='row_number',
            new_name='circuit_number',
        ),
    ]
