# Generated by Django 4.0.6 on 2023-01-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0030_rename_row_number_circuit_circuit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelmeter',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
