# Generated by Django 4.0.6 on 2023-02-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0031_alter_panelmeter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelmeter',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
