# Generated by Django 4.0.6 on 2023-02-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0032_alter_panelmeter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='categories'),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='total_commodity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Total cost'),
        ),
    ]
