# Generated by Django 4.0.6 on 2023-02-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0033_circuitcategory_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='panel_image',
            field=models.ImageField(blank=True, null=True, upload_to='panels'),
        ),
    ]
