# Generated by Django 4.0.6 on 2023-02-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0036_utilitybill_line_utilitybill_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='number_of_phases',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='panelmeterchannel',
            name='current',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='panelmeterchannel',
            name='voltage_refrence_type',
            field=models.CharField(blank=True, choices=[('V1', 'V1'), ('V2', 'V2'), ('V3', 'V3')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='panelmeterchannel',
            name='voltage_refrence_value',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
