# Generated by Django 4.0.6 on 2023-02-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0037_meter_name_meter_number_of_phases_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='number_of_phases',
        ),
        migrations.AddField(
            model_name='panelmeter',
            name='number_of_phases',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
    ]
