# Generated by Django 4.0.6 on 2023-03-05 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0038_remove_meter_number_of_phases_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='panel_images')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_images', to='sustainergy_dashboard.panel')),
            ],
        ),
    ]
